# Generated by Django 2.2 on 2019-10-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('credits', models.CharField(max_length=6)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AddFaculty',
            fields=[
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('employee_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('dob', models.DateField(null=True)),
                ('department', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeanNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DeanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LastDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=15)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_assign', models.CharField(default='', max_length=20)),
                ('semester', models.CharField(default='', max_length=20)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.AddCourse')),
                ('employee_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.AddFaculty')),
            ],
        ),
    ]
