# Generated by Django 2.2 on 2019-10-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('dean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('registration_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('employee_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dean.AddFaculty')),
            ],
        ),
    ]
