# Generated by Django 2.2 on 2019-08-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='credits',
        ),
    ]
